/** @format */

import React from "react";
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { FileDown, Printer, X } from "lucide-react";
import { useCurrency } from "@/hooks/useCurrency";

interface DailyReportDialogProps {
	open: boolean;
	onClose: () => void;
	reportData: any;
	onDownload: () => void;
	user: any;
}

export const DailyReportDialog: React.FC<DailyReportDialogProps> = ({
	open,
	onClose,
	reportData,
	onDownload,
	user,
}) => {
	const { format: formatCurrency } = useCurrency();

	if (!reportData) return null;

	const drinksTotal = reportData.inventory.reduce((sum: number, item: any) => sum + item.totalSales, 0);
	const foodTotal = reportData.foodSales.reduce((sum: number, item: any) => sum + item.totalSales, 0);
	const grandTotal = drinksTotal + foodTotal;

	return (
		<Dialog open={open} onOpenChange={onClose}>
			<DialogContent className="max-w-4xl max-h-[90vh] flex flex-col p-0 overflow-hidden">
				<DialogHeader className="px-6 py-4 border-b">
					<div className="flex items-center justify-between">
						<div>
							<DialogTitle className="text-2xl font-bold">Daily Sales & Inventory Report</DialogTitle>
							<div className="flex items-center gap-2 mt-1 text-sm text-gray-500">
								<span>Generated by: <span className="font-semibold text-gray-900">{user?.username || "Admin"}</span></span>
								<span className="w-1 h-1 bg-gray-300 rounded-full"></span>
								<span className="bg-blue-50 text-blue-700 px-2 py-0.5 rounded text-xs font-medium uppercase">{user?.role || "Manager"}</span>
							</div>
						</div>
						<div className="text-sm text-gray-500 font-normal text-right">
							<div className="font-medium text-gray-900">{reportData.date}</div>
							<div>Report Summary</div>
						</div>
					</div>
				</DialogHeader>

				<div className="flex-1 px-6 py-4 overflow-y-auto">
					<div className="space-y-8">
						{/* Drinks Inventory Section */}
						<section>
							<h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
								<span className="w-2 h-6 bg-blue-600 rounded-full"></span>
								Drinks Inventory Reconciliation
							</h3>
							<div className="border rounded-lg overflow-hidden">
								<Table>
									<TableHeader className="bg-gray-50">
										<TableRow>
											<TableHead className="font-bold">Item Name</TableHead>
											<TableHead className="text-right">Opening</TableHead>
											<TableHead className="text-right">Added</TableHead>
											<TableHead className="text-right">Sold</TableHead>
											<TableHead className="text-right">Sales</TableHead>
											<TableHead className="text-right">Left</TableHead>
										</TableRow>
									</TableHeader>
									<TableBody>
										{reportData.inventory.map((item: any) => (
											<TableRow key={item.id}>
												<TableCell className="font-medium">{item.name}</TableCell>
												<TableCell className="text-right">{item.openingStock}</TableCell>
												<TableCell className="text-right text-green-600">+{item.added}</TableCell>
												<TableCell className="text-right text-blue-600">{item.sold}</TableCell>
												<TableCell className="text-right font-semibold">{formatCurrency(item.totalSales)}</TableCell>
												<TableCell className="text-right">{item.stockLeft}</TableCell>
											</TableRow>
										))}
									</TableBody>
								</Table>
							</div>
						</section>

						{/* Food Sales Section */}
						<section>
							<h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
								<span className="w-2 h-6 bg-green-600 rounded-full"></span>
								Food Sales Summary
							</h3>
							<div className="border rounded-lg overflow-hidden">
								<Table>
									<TableHeader className="bg-gray-50">
										<TableRow>
											<TableHead className="font-bold">Item Name</TableHead>
											<TableHead className="text-right">Price</TableHead>
											<TableHead className="text-right">Qty Sold</TableHead>
											<TableHead className="text-right">Total Revenue</TableHead>
										</TableRow>
									</TableHeader>
									<TableBody>
										{reportData.foodSales.length === 0 ? (
											<TableRow>
												<TableCell colSpan={4} className="text-center py-4 text-gray-500 italic">No food sales recorded for this date.</TableCell>
											</TableRow>
										) : (
											reportData.foodSales.map((item: any, idx: number) => (
												<TableRow key={idx}>
													<TableCell className="font-medium">{item.name}</TableCell>
													<TableCell className="text-right">{formatCurrency(item.price)}</TableCell>
													<TableCell className="text-right">{item.quantity}</TableCell>
													<TableCell className="text-right font-semibold">{formatCurrency(item.totalSales)}</TableCell>
												</TableRow>
											))
										)}
									</TableBody>
								</Table>
							</div>
						</section>

						{/* Totals Section */}
						<div className="bg-gray-50 p-6 rounded-xl border-2 border-dashed border-gray-200">
							<div className="grid grid-cols-1 md:grid-cols-3 gap-6">
								<div className="space-y-1">
									<p className="text-sm text-gray-500 uppercase tracking-wider">Drinks Revenue</p>
									<p className="text-2xl font-bold text-blue-600">{formatCurrency(drinksTotal)}</p>
								</div>
								<div className="space-y-1">
									<p className="text-sm text-gray-500 uppercase tracking-wider">Food Revenue</p>
									<p className="text-2xl font-bold text-green-600">{formatCurrency(foodTotal)}</p>
								</div>
								<div className="space-y-1 border-t md:border-t-0 md:border-l pt-4 md:pt-0 md:pl-6">
									<p className="text-sm text-gray-500 uppercase tracking-wider">Grand Total</p>
									<p className="text-3xl font-black text-gray-900">{formatCurrency(grandTotal)}</p>
								</div>
							</div>
						</div>
					</div>
				</div>

				<DialogFooter className="px-6 py-4 border-t bg-gray-50 gap-3">
					<Button variant="outline" onClick={onClose} className="flex items-center gap-2">
						<X className="h-4 w-4" />
						Close
					</Button>
					<Button onClick={onDownload} className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700">
						<FileDown className="h-4 w-4" />
						Download PDF Report
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
};
